export default function DisclaimerPage() {
  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="text-4xl font-bold mb-8">Disclaimer</h1>
      <div className="prose max-w-none">
        <p>Last updated: [Current Date]</p>
        <h2>1. Purpose of CC Generator</h2>
        <p>CC Generator is a tool designed for testing and educational purposes only. The credit card numbers generated by this tool are not real and cannot be used for actual transactions.</p>
        <h2>2. No Real Financial Data</h2>
        <p>The numbers generated by CC Generator are not connected to any real bank accounts or credit card accounts. They are created using algorithms that produce numbers that pass basic validation checks.</p>
        <h2>3. Prohibited Use</h2>
        <p>It is strictly prohibited to use CC Generator or the numbers it generates for any fraudulent or illegal activities. This includes, but is not limited to, attempting to make purchases, accessing accounts, or any other activities that could be considered credit card fraud.</p>
        <h2>4. No Liability</h2>
        <p>The creators and operators of CC Generator accept no liability for any misuse of this tool or the numbers it generates. Users are solely responsible for their use of CC Generator and any consequences that may arise from such use.</p>
        <h2>5. No Warranty</h2>
        <p>CC Generator is provided "as is" without any warranties, express or implied. We do not guarantee the accuracy, completeness, or usefulness of the numbers generated.</p>
        <h2>6. Changes to This Disclaimer</h2>
        <p>We reserve the right to modify this disclaimer at any time. Changes will be effective immediately upon posting on this page.</p>
      </div>
    </div>
  )
}

